export const HomePageDetails =[
    {
        "id": 39,
        "position": 2,
        "title": "ViaSat-3 Americas Mission",
        "subtitle": "Upcoming Launch",
        "link": "/launches/mission/?missionId=ViaSat-3-Americas",
        "linkInNewTab": false,
        "callToAction": "Watch",
        "alignContent": "left",
        "backgroundDesktop": {
            "id": 353,
            "name": "homepage_desktop.jpg",
            "alternativeText": "homepage_desktop.jpg",
            "caption": "homepage_desktop.jpg",
            "width": 2600,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_homepage_desktop_6afe3be774.jpg",
                    "hash": "large_homepage_desktop_6afe3be774",
                    "mime": "image/jpeg",
                    "name": "large_homepage_desktop.jpg",
                    "path": null,
                    "size": 41.65,
                    "width": 1000,
                    "height": 462
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_homepage_desktop_6afe3be774.jpg",
                    "hash": "small_homepage_desktop_6afe3be774",
                    "mime": "image/jpeg",
                    "name": "small_homepage_desktop.jpg",
                    "path": null,
                    "size": 12.69,
                    "width": 500,
                    "height": 231
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_homepage_desktop_6afe3be774.jpg",
                    "hash": "medium_homepage_desktop_6afe3be774",
                    "mime": "image/jpeg",
                    "name": "medium_homepage_desktop.jpg",
                    "path": null,
                    "size": 25.58,
                    "width": 750,
                    "height": 346
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_homepage_desktop_6afe3be774.jpg",
                    "hash": "thumbnail_homepage_desktop_6afe3be774",
                    "mime": "image/jpeg",
                    "name": "thumbnail_homepage_desktop.jpg",
                    "path": null,
                    "size": 4.13,
                    "width": 245,
                    "height": 113
                }
            },
            "hash": "homepage_desktop_6afe3be774",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 217.14,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/homepage_desktop_6afe3be774.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/83/87",
            "createdAt": "2023-04-26T11:51:59.723Z",
            "updatedAt": "2023-04-26T11:51:59.723Z"
        },
        "backgroundMobile": {
            "id": 354,
            "name": "homepage_mobile.jpg",
            "alternativeText": "homepage_mobile.jpg",
            "caption": "homepage_mobile.jpg",
            "width": 840,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_homepage_mobile_d2f2e5ca75.jpg",
                    "hash": "large_homepage_mobile_d2f2e5ca75",
                    "mime": "image/jpeg",
                    "name": "large_homepage_mobile.jpg",
                    "path": null,
                    "size": 82.21,
                    "width": 700,
                    "height": 1000
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_homepage_mobile_d2f2e5ca75.jpg",
                    "hash": "small_homepage_mobile_d2f2e5ca75",
                    "mime": "image/jpeg",
                    "name": "small_homepage_mobile.jpg",
                    "path": null,
                    "size": 24.56,
                    "width": 350,
                    "height": 500
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_homepage_mobile_d2f2e5ca75.jpg",
                    "hash": "medium_homepage_mobile_d2f2e5ca75",
                    "mime": "image/jpeg",
                    "name": "medium_homepage_mobile.jpg",
                    "path": null,
                    "size": 49.89,
                    "width": 525,
                    "height": 750
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_homepage_mobile_d2f2e5ca75.jpg",
                    "hash": "thumbnail_homepage_mobile_d2f2e5ca75",
                    "mime": "image/jpeg",
                    "name": "thumbnail_homepage_mobile.jpg",
                    "path": null,
                    "size": 3.75,
                    "width": 109,
                    "height": 156
                }
            },
            "hash": "homepage_mobile_d2f2e5ca75",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 112.25,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/homepage_mobile_d2f2e5ca75.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/83/87",
            "createdAt": "2023-04-26T11:51:59.833Z",
            "updatedAt": "2023-04-26T11:51:59.833Z"
        }
    },
    {
        "id": 38,
        "position": 4,
        "title": "Starlink Mission",
        "subtitle": "RECENT LAUNCH",
        "link": "/launches/mission/?missionId=sl3-5-pl",
        "linkInNewTab": false,
        "callToAction": "REWATCH",
        "alignContent": "left",
        "backgroundDesktop": {
            "id": 361,
            "name": "Starlink-G3-5_San_Mig_5920_Desktop.jpg",
            "alternativeText": "Starlink-G3-5_San_Mig_5920_Desktop.jpg",
            "caption": "Starlink-G3-5_San_Mig_5920_Desktop.jpg",
            "width": 2600,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77.jpg",
                    "hash": "large_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77",
                    "mime": "image/jpeg",
                    "name": "large_Starlink-G3-5_San_Mig_5920_Desktop.jpg",
                    "path": null,
                    "size": 8.53,
                    "width": 1000,
                    "height": 462
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77.jpg",
                    "hash": "small_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77",
                    "mime": "image/jpeg",
                    "name": "small_Starlink-G3-5_San_Mig_5920_Desktop.jpg",
                    "path": null,
                    "size": 3.19,
                    "width": 500,
                    "height": 231
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77.jpg",
                    "hash": "medium_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77",
                    "mime": "image/jpeg",
                    "name": "medium_Starlink-G3-5_San_Mig_5920_Desktop.jpg",
                    "path": null,
                    "size": 5.59,
                    "width": 750,
                    "height": 346
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77.jpg",
                    "hash": "thumbnail_Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77",
                    "mime": "image/jpeg",
                    "name": "thumbnail_Starlink-G3-5_San_Mig_5920_Desktop.jpg",
                    "path": null,
                    "size": 1.38,
                    "width": 245,
                    "height": 113
                }
            },
            "hash": "Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 44.91,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/Starlink_G3_5_San_Mig_5920_Desktop_bce3e49b77.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/88",
            "createdAt": "2023-04-27T16:53:56.427Z",
            "updatedAt": "2023-04-27T16:53:56.427Z"
        },
        "backgroundMobile": {
            "id": 357,
            "name": "Starlink G3-5_San_Mig_5920_Mobile.jpg",
            "alternativeText": "Starlink G3-5_San_Mig_5920_Mobile.jpg",
            "caption": "Starlink G3-5_San_Mig_5920_Mobile.jpg",
            "width": 840,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637.jpg",
                    "hash": "large_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637",
                    "mime": "image/jpeg",
                    "name": "large_Starlink G3-5_San_Mig_5920_Mobile.jpg",
                    "path": null,
                    "size": 15.24,
                    "width": 700,
                    "height": 1000
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637.jpg",
                    "hash": "small_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637",
                    "mime": "image/jpeg",
                    "name": "small_Starlink G3-5_San_Mig_5920_Mobile.jpg",
                    "path": null,
                    "size": 5.36,
                    "width": 350,
                    "height": 500
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637.jpg",
                    "hash": "medium_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637",
                    "mime": "image/jpeg",
                    "name": "medium_Starlink G3-5_San_Mig_5920_Mobile.jpg",
                    "path": null,
                    "size": 9.86,
                    "width": 525,
                    "height": 750
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637.jpg",
                    "hash": "thumbnail_Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637",
                    "mime": "image/jpeg",
                    "name": "thumbnail_Starlink G3-5_San_Mig_5920_Mobile.jpg",
                    "path": null,
                    "size": 1.29,
                    "width": 109,
                    "height": 156
                }
            },
            "hash": "Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 19.58,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/Starlink_G3_5_San_Mig_5920_Mobile_e6fd4b8637.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/88",
            "createdAt": "2023-04-27T16:48:08.132Z",
            "updatedAt": "2023-04-27T16:48:08.132Z"
        }
    },
    {
        "id": 3,
        "position": 5,
        "title": "Starship Selected by NASA to Support Sustained Lunar Exploration",
        "subtitle": null,
        "link": "/updates/#sustained-lunar-exploration",
        "linkInNewTab": false,
        "callToAction": "Learn More",
        "alignContent": "left",
        "backgroundDesktop": {
            "id": 9,
            "name": "Homepage_Desktop.webp",
            "alternativeText": "Homepage_Desktop.webp",
            "caption": "Homepage_Desktop.webp",
            "width": 2600,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_Homepage_Desktop_5ebdeb0c6c.webp",
                    "hash": "large_Homepage_Desktop_5ebdeb0c6c",
                    "mime": "image/webp",
                    "name": "large_Homepage_Desktop.webp",
                    "path": null,
                    "size": 21.26,
                    "width": 1000,
                    "height": 462
                },
                "small": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_Homepage_Desktop_5ebdeb0c6c.webp",
                    "hash": "small_Homepage_Desktop_5ebdeb0c6c",
                    "mime": "image/webp",
                    "name": "small_Homepage_Desktop.webp",
                    "path": null,
                    "size": 6.54,
                    "width": 500,
                    "height": 231
                },
                "medium": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_Homepage_Desktop_5ebdeb0c6c.webp",
                    "hash": "medium_Homepage_Desktop_5ebdeb0c6c",
                    "mime": "image/webp",
                    "name": "medium_Homepage_Desktop.webp",
                    "path": null,
                    "size": 13.33,
                    "width": 750,
                    "height": 346
                },
                "thumbnail": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_Homepage_Desktop_5ebdeb0c6c.webp",
                    "hash": "thumbnail_Homepage_Desktop_5ebdeb0c6c",
                    "mime": "image/webp",
                    "name": "thumbnail_Homepage_Desktop.webp",
                    "path": null,
                    "size": 2.19,
                    "width": 245,
                    "height": 113
                }
            },
            "hash": "Homepage_Desktop_5ebdeb0c6c",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 130.56,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/Homepage_Desktop_5ebdeb0c6c.webp",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/4",
            "createdAt": "2022-12-07T20:26:39.762Z",
            "updatedAt": "2022-12-07T20:26:39.762Z"
        },
        "backgroundMobile": {
            "id": 8,
            "name": "Homepage_Mobile.webp",
            "alternativeText": "Homepage_Mobile.webp",
            "caption": "Homepage_Mobile.webp",
            "width": 840,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_Homepage_Mobile_647a5aee3b.webp",
                    "hash": "large_Homepage_Mobile_647a5aee3b",
                    "mime": "image/webp",
                    "name": "large_Homepage_Mobile.webp",
                    "path": null,
                    "size": 35.38,
                    "width": 700,
                    "height": 1000
                },
                "small": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_Homepage_Mobile_647a5aee3b.webp",
                    "hash": "small_Homepage_Mobile_647a5aee3b",
                    "mime": "image/webp",
                    "name": "small_Homepage_Mobile.webp",
                    "path": null,
                    "size": 11.39,
                    "width": 350,
                    "height": 500
                },
                "medium": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_Homepage_Mobile_647a5aee3b.webp",
                    "hash": "medium_Homepage_Mobile_647a5aee3b",
                    "mime": "image/webp",
                    "name": "medium_Homepage_Mobile.webp",
                    "path": null,
                    "size": 22.72,
                    "width": 525,
                    "height": 750
                },
                "thumbnail": {
                    "ext": ".webp",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_Homepage_Mobile_647a5aee3b.webp",
                    "hash": "thumbnail_Homepage_Mobile_647a5aee3b",
                    "mime": "image/webp",
                    "name": "thumbnail_Homepage_Mobile.webp",
                    "path": null,
                    "size": 1.8,
                    "width": 109,
                    "height": 156
                }
            },
            "hash": "Homepage_Mobile_647a5aee3b",
            "ext": ".webp",
            "mime": "image/webp",
            "size": 58.91,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/Homepage_Mobile_647a5aee3b.webp",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/4",
            "createdAt": "2022-12-07T20:26:37.247Z",
            "updatedAt": "2022-12-07T20:26:37.247Z"
        }
    },
    {
        "id": 41,
        "position": 3,
        "title": "SES O3b mPOWER Mission",
        "subtitle": "Recent Launch",
        "link": "/launches/mission/?missionId=SES-03b-mPOWERb-pl",
        "linkInNewTab": false,
        "callToAction": "REWATCH",
        "alignContent": "left",
        "backgroundDesktop": {
            "id": 368,
            "name": "homepage_1054_desktop.jpg",
            "alternativeText": "homepage_1054_desktop.jpg",
            "caption": "homepage_1054_desktop.jpg",
            "width": 2600,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_homepage_1054_desktop_a52a06e9f7.jpg",
                    "hash": "large_homepage_1054_desktop_a52a06e9f7",
                    "mime": "image/jpeg",
                    "name": "large_homepage_1054_desktop.jpg",
                    "path": null,
                    "size": 19.96,
                    "width": 1000,
                    "height": 462
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_homepage_1054_desktop_a52a06e9f7.jpg",
                    "hash": "small_homepage_1054_desktop_a52a06e9f7",
                    "mime": "image/jpeg",
                    "name": "small_homepage_1054_desktop.jpg",
                    "path": null,
                    "size": 6.94,
                    "width": 500,
                    "height": 231
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_homepage_1054_desktop_a52a06e9f7.jpg",
                    "hash": "medium_homepage_1054_desktop_a52a06e9f7",
                    "mime": "image/jpeg",
                    "name": "medium_homepage_1054_desktop.jpg",
                    "path": null,
                    "size": 12.59,
                    "width": 750,
                    "height": 346
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_homepage_1054_desktop_a52a06e9f7.jpg",
                    "hash": "thumbnail_homepage_1054_desktop_a52a06e9f7",
                    "mime": "image/jpeg",
                    "name": "thumbnail_homepage_1054_desktop.jpg",
                    "path": null,
                    "size": 2.66,
                    "width": 245,
                    "height": 113
                }
            },
            "hash": "homepage_1054_desktop_a52a06e9f7",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 126.55,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/homepage_1054_desktop_a52a06e9f7.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/86/90",
            "createdAt": "2023-04-28T22:48:17.045Z",
            "updatedAt": "2023-04-28T22:48:17.045Z"
        },
        "backgroundMobile": {
            "id": 366,
            "name": "homepage_1054_1_mobile.jpg",
            "alternativeText": "homepage_1054_1_mobile.jpg",
            "caption": "homepage_1054_1_mobile.jpg",
            "width": 840,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_homepage_1054_1_mobile_cad99a6947.jpg",
                    "hash": "large_homepage_1054_1_mobile_cad99a6947",
                    "mime": "image/jpeg",
                    "name": "large_homepage_1054_1_mobile.jpg",
                    "path": null,
                    "size": 41.08,
                    "width": 700,
                    "height": 1000
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_homepage_1054_1_mobile_cad99a6947.jpg",
                    "hash": "small_homepage_1054_1_mobile_cad99a6947",
                    "mime": "image/jpeg",
                    "name": "small_homepage_1054_1_mobile.jpg",
                    "path": null,
                    "size": 11.36,
                    "width": 350,
                    "height": 500
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_homepage_1054_1_mobile_cad99a6947.jpg",
                    "hash": "medium_homepage_1054_1_mobile_cad99a6947",
                    "mime": "image/jpeg",
                    "name": "medium_homepage_1054_1_mobile.jpg",
                    "path": null,
                    "size": 23.06,
                    "width": 525,
                    "height": 750
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_homepage_1054_1_mobile_cad99a6947.jpg",
                    "hash": "thumbnail_homepage_1054_1_mobile_cad99a6947",
                    "mime": "image/jpeg",
                    "name": "thumbnail_homepage_1054_1_mobile.jpg",
                    "path": null,
                    "size": 2.14,
                    "width": 109,
                    "height": 156
                }
            },
            "hash": "homepage_1054_1_mobile_cad99a6947",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 59.67,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/homepage_1054_1_mobile_cad99a6947.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/86/90",
            "createdAt": "2023-04-28T22:48:16.672Z",
            "updatedAt": "2023-04-28T22:48:16.672Z"
        }
    },
    {
        "id": 34,
        "position": 1,
        "title": "Starship Flight Test",
        "subtitle": "RECENT",
        "link": "/launches/mission/?missionId=starship-flight-test",
        "linkInNewTab": false,
        "callToAction": "REWATCH",
        "alignContent": "left",
        "backgroundDesktop": {
            "id": 351,
            "name": "STARSHIP_Testflight_DESKTOP.jpg",
            "alternativeText": "STARSHIP_Testflight_DESKTOP.jpg",
            "caption": "STARSHIP_Testflight_DESKTOP.jpg",
            "width": 2600,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_STARSHIP_Testflight_DESKTOP_2b3bea613a.jpg",
                    "hash": "large_STARSHIP_Testflight_DESKTOP_2b3bea613a",
                    "mime": "image/jpeg",
                    "name": "large_STARSHIP_Testflight_DESKTOP.jpg",
                    "path": null,
                    "size": 16.83,
                    "width": 1000,
                    "height": 462
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_STARSHIP_Testflight_DESKTOP_2b3bea613a.jpg",
                    "hash": "small_STARSHIP_Testflight_DESKTOP_2b3bea613a",
                    "mime": "image/jpeg",
                    "name": "small_STARSHIP_Testflight_DESKTOP.jpg",
                    "path": null,
                    "size": 5.57,
                    "width": 500,
                    "height": 231
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_STARSHIP_Testflight_DESKTOP_2b3bea613a.jpg",
                    "hash": "medium_STARSHIP_Testflight_DESKTOP_2b3bea613a",
                    "mime": "image/jpeg",
                    "name": "medium_STARSHIP_Testflight_DESKTOP.jpg",
                    "path": null,
                    "size": 10.23,
                    "width": 750,
                    "height": 346
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_STARSHIP_Testflight_DESKTOP_2b3bea613a.jpg",
                    "hash": "thumbnail_STARSHIP_Testflight_DESKTOP_2b3bea613a",
                    "mime": "image/jpeg",
                    "name": "thumbnail_STARSHIP_Testflight_DESKTOP.jpg",
                    "path": null,
                    "size": 2.1,
                    "width": 245,
                    "height": 113
                }
            },
            "hash": "STARSHIP_Testflight_DESKTOP_2b3bea613a",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 153.78,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/STARSHIP_Testflight_DESKTOP_2b3bea613a.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/81",
            "createdAt": "2023-04-20T18:07:11.498Z",
            "updatedAt": "2023-04-20T18:07:11.498Z"
        },
        "backgroundMobile": {
            "id": 350,
            "name": "STARSHIP_Testflight_MOBILE.jpg",
            "alternativeText": "STARSHIP_Testflight_MOBILE.jpg",
            "caption": "STARSHIP_Testflight_MOBILE.jpg",
            "width": 840,
            "height": 1200,
            "formats": {
                "large": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/large_STARSHIP_Testflight_MOBILE_3be065456e.jpg",
                    "hash": "large_STARSHIP_Testflight_MOBILE_3be065456e",
                    "mime": "image/jpeg",
                    "name": "large_STARSHIP_Testflight_MOBILE.jpg",
                    "path": null,
                    "size": 28.74,
                    "width": 700,
                    "height": 1000
                },
                "small": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/small_STARSHIP_Testflight_MOBILE_3be065456e.jpg",
                    "hash": "small_STARSHIP_Testflight_MOBILE_3be065456e",
                    "mime": "image/jpeg",
                    "name": "small_STARSHIP_Testflight_MOBILE.jpg",
                    "path": null,
                    "size": 8.64,
                    "width": 350,
                    "height": 500
                },
                "medium": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/medium_STARSHIP_Testflight_MOBILE_3be065456e.jpg",
                    "hash": "medium_STARSHIP_Testflight_MOBILE_3be065456e",
                    "mime": "image/jpeg",
                    "name": "medium_STARSHIP_Testflight_MOBILE.jpg",
                    "path": null,
                    "size": 17.14,
                    "width": 525,
                    "height": 750
                },
                "thumbnail": {
                    "ext": ".jpg",
                    "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/thumbnail_STARSHIP_Testflight_MOBILE_3be065456e.jpg",
                    "hash": "thumbnail_STARSHIP_Testflight_MOBILE_3be065456e",
                    "mime": "image/jpeg",
                    "name": "thumbnail_STARSHIP_Testflight_MOBILE.jpg",
                    "path": null,
                    "size": 1.73,
                    "width": 109,
                    "height": 156
                }
            },
            "hash": "STARSHIP_Testflight_MOBILE_3be065456e",
            "ext": ".jpg",
            "mime": "image/jpeg",
            "size": 40.09,
            "url": "https://sxcontent9668.azureedge.us/cms-assets/assets/STARSHIP_Testflight_MOBILE_3be065456e.jpg",
            "previewUrl": null,
            "provider": "strapi-provider-upload-azure-storage",
            "provider_metadata": null,
            "folderPath": "/81",
            "createdAt": "2023-04-20T18:07:10.522Z",
            "updatedAt": "2023-04-20T18:07:10.522Z"
        }
    }
]